use_frameworks!

target 'OutsmartCommons_Example' do
  pod 'OutsmartCommons', :path => '../'

  target 'OutsmartCommons_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
